let arr = [1, 9, 12, 2, 3, 4, 5, 8];
// arr.fill(12, 2, 5);
// arr.pop();
// arr.push(56);
// arr.shift();
// arr.unshift(45);
// arr.reverse();
// arr.sort();
// arr.sort((a, b) => a - b);
arr.splice(1, 3, "JS", "num");
console.log(arr);
